### ISSUE TITLE
python2 score_base.py help

### ISSUE THREAD

**Issue by icebowl** [facebook/fbctf#641]
High School Level bfctf game on a LAN.  Lots of fun!
We are trying to deploy a base using this code posted python2 score_base.py
We have not modified the code. 
https://github.com/facebook/fbctf/blob/master/extra/score_base.py
We can curl from the server: 
curl 192.168.1.13:12345
[{"check": "8d81990a9b00f0775b7b39604c098418", "team": "icebowl"}]

The base points are not getting updated.
Please throw us a bone.

**Comment by icebowl** [comment]
Solved by Bryan1998 https://gist.github.com/Bryan1998

**Comment by jbooz1** [comment]
> Solved by Bryan1998 https://gist.github.com/Bryan1998

Not sure how this solved the issue. I tried what is here and still cannot see the updates.
Can you provide more information?
